BUILD_DIRECTORY = build
RESOURCE_DIRECTORY = $(BUILD_DIRECTORY)/resources
VERSIONS_DIRECTORY = $(BUILD_DIRECTORY)/versions
SERVER_BIN_RESOURCE_DIRECTORY = $(RESOURCE_DIRECTORY)/server

MINECRAFT_VERION = 1.19.73.02
MINECRAFT_VERSION_FILE=$(VERSIONS_DIRECTORY)/minecraft-server-$(MINECRAFT_VERION)

help:
	@echo  'TODO usage'

init:
	mkdir -p $(BUILD_DIRECTORY)
	mkdir -p $(RESOURCE_DIRECTORY)
	mkdir -p $(VERSIONS_DIRECTORY)

build: init download-resources
	
download-resources: $(SERVER_BIN_RESOURCE_DIRECTORY)

$(SERVER_BIN_RESOURCE_DIRECTORY): download-server.sh $(MINECRAFT_VERSION_FILE)
	rm -rf $(SERVER_BIN_RESOURCE_DIRECTORY)
	./download-server.sh $(SERVER_BIN_RESOURCE_DIRECTORY) $(MINECRAFT_VERION)

$(MINECRAFT_VERSION_FILE):
	touch $(MINECRAFT_VERSION_FILE)

clean:
	rm -rf $(BUILD_DIRECTORY)
